# Copyright 2020 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
version: '3'
services:
  notebook:
    user: root
    build:
      context: ./tools/notebook
      dockerfile: ./Dockerfile
    image: gcr.io/cloud-healthcare-containers/cloud-healthcare-data-harmonization-notebook:latest
    command: start-notebook.sh --FileCheckpoints.checkpoint_dir=/tmp --NotebookApp.ip='*' --NotebookApp.open_browser=False --NotebookApp.port=8888 --NotebookApp.allow_origin='*'
    ports:
      - "${NOTEBOOK_PORT:-8888}:8888"
    volumes:
      - "$NOTEBOOK_WORKING_DIR:/home/jovyan"
      - "$NOTEBOOK_SERVICE_ACCOUNT_DIR:/home/jovyan/.config/gcloud"
      - "$NOTEBOOK_FUNCTION_LIBRARY_DIR:/home/jovyan/function_library"
    environment:
      - NOTEBOOK_GRPC_HOST=grpc
      - NB_UID=$NOTEBOOK_UID
      - JUPYTER_ENABLE_LAB='yes'
      - GOOGLE_APPLICATION_CREDENTIALS=/home/jovyan/.config/gcloud/$NOTEBOOK_SERVICE_ACCOUNT_FILENAME
    depends_on:
      - grpc
  grpc:
    user: root
    build:
      context: .
      dockerfile: ./tools/notebook/extensions/wstl/Dockerfile
    entrypoint: ["/etc/wstl/bin/main",  "-host=0.0.0.0"]
    image: "gcr.io/cloud-healthcare-containers/cloud-healthcare-data-harmonization-services:latest"
    volumes:
      - "$NOTEBOOK_WORKING_DIR:/home/jovyan"
      - "$NOTEBOOK_SERVICE_ACCOUNT_DIR:/home/jovyan/.config/gcloud"
      - "$NOTEBOOK_FUNCTION_LIBRARY_DIR:/home/jovyan/function_library"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
    environment:
      - DH_ROOT=$PWD
      - GOOGLE_APPLICATION_CREDENTIALS=/home/jovyan/.config/gcloud/$NOTEBOOK_SERVICE_ACCOUNT_FILENAME
